---
- name: Get node_exporter installed version
  ansible.builtin.command: "node_exporter --version"
  register: node_exporter_check_info
  changed_when: false
  failed_when: false

- name: Check if node_exporter is already installed with the correct version
  ansible.builtin.set_fact:
    node_exporter_already_installed: "{{ node_exporter_check_info is defined and node_exporter_check_info.stdout is ansible.builtin.search(node_exporter_version) }}"

- name: Install node-exporter
  ansible.builtin.include_tasks: "install-node-exporter.yml"
  when: not node_exporter_already_installed

- name: Configure node-exporter service
  ansible.builtin.import_tasks: "configure-node-exporter.yml"
