---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    node_exporter_version: "1.9.0"

  tasks:
    - name: Include willbrid.node_exporter
      ansible.builtin.include_role:
        name: "willbrid.node_exporter"
