---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    node_exporter_version: "1.9.0"
    ansible_architecture: "amd64"  # Because the gather_facts is disabled
  tasks:
    - name: Include willbrid.node_exporter
      ansible.builtin.include_role:
        name: "willbrid.node_exporter"
