---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    node_exporter_version: "1.9.0"
    node_exporter_bin_dir: "/usr/local/bin"

  tasks:
    - name: Get node exporter binary version
      ansible.builtin.command: "{{ node_exporter_bin_dir }}/node_exporter --version"
      register: node_exporter_info
      changed_when: false
    - name: Check node_exporter correct version
      ansible.builtin.assert:
        that:
          - "node_exporter_version in node_exporter_info.stdout"
    - name: Get node_exporter service status
      ansible.builtin.systemd:
        name: node_exporter
        state: started
      register: node_exporter_status
    - name: Check that node_exporter service is running
      ansible.builtin.assert:
        that:
          - "node_exporter_status.status.ActiveState == 'active'"
